# ===============================
# Cấu hình Ứng dụng & Server
# ===============================
spring.application.name=quan_ly_ho_so_backend
server.port=8080

# ===============================
# Cấu hình kết nối MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/quan_ly_ho_so?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=tien0399007905
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Cấu hình Hibernate cho MySQL
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Cấu hình Upload File (Minh chứng)
# ===============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
app.upload-dir=uploads

# ===============================
# Cấu hình Bảo mật (JWT & Logs)
# ===============================
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG